### PR TITLE
minor tweaks to support multi-dc, multi-cluster VCs + CNV

### PR DESCRIPTION
**Pull request by smarunich**
+dc option to support multiple dcs
+cluster option to support multiple clusters
+nested virtualization to support CNV

### CODE REVIEW

**Comment by cptmorgan-rh** [comment]
Sergey,

Have you deployed a cluster and then used the destroy script to verify that it works properly with the new changes?

Since this script is meant for a Lab environment it was written with the intend that a user would have 1 DC and 1 Cluster.

**Comment by smarunich** [comment]
Morgan,

good point, updated the destroyer to respect the changes and have tested, should be good to merge.

Cheers,
Sergey

**Comment by cptmorgan-rh** [comment]
Thanks for updating. I am deploying a cluster now and will destroy once done. If all goes well I will merge.

Thanks!

**Comment by cptmorgan-rh** [comment]
Merged. Thank you Sergey.

**Pull request merged**
